name: Deploy Images - PROD

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'  # Required for workload identity federation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_PROD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_PROD_SERVICE_ACCOUNT }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: '${{ vars.DOCKER_REGISTRY }}'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.GCP_PROJECT_PROD }}/${{ vars.DOCKER_REPOSITORY }}:${{ github.ref_name }}
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.GCP_PROJECT_PROD }}/${{ vars.DOCKER_REPOSITORY }}:latest
