name: deploy-image-prod

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: PROD
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_PROD_SERVICE_ACCOUNT }}'

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker ${{ vars.DOCKROCKER_REGISTRY }} --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: '${{ vars.DOCKER_REGISTRY }}/${{ vars.GCP_PROJECT_PROD }}/${{ vars.DOCKER_REPOSITORY }}/my-app:${{ github.ref_name }}'
